### ISSUE TITLE
build with curl  8.2.1 failed, some macros are deprecated. 

### ISSUE THREAD

**Issue by cagev** [alibaba/PhotonLibOS#435]
build on ubuntu 23.10 , with curl 8.2.1 

errors: 

/home/arthur/work/photondemo/opt/PhotonLibOS/net/curl.h: In member function ‘long int photon::net::cURL::PUT(const char*, R*, W*, uint64_t)’:
/home/arthur/work/photondemo/opt/PhotonLibOS/net/curl.h:416:16: error: ‘CURLOPT_PUT’ is deprecated: since 7.12.1. Use **CURLOPT_UPLOAD** [-Werror=deprecated-declarations]
  416 |         setopt(CURLOPT_PUT, 1L);

/home/arthur/work/photondemo/opt/PhotonLibOS/fs/httpfs/../../net/curl.h: In constructor ‘photon::net::cURL::cURL()’:
/home/arthur/work/photondemo/opt/PhotonLibOS/fs/httpfs/../../net/curl.h:243:16: error: ‘CURLOPT_DNS_USE_GLOBAL_CACHE’ is deprecated: since 7.11.1. Use **CURLOPT_SHARE** [-Werror=deprecated-declarations]
  243 |         setopt(CURLOPT_DNS_USE_GLOBAL_CACHE, 0L);

just update the macos to fix it with different curl versions.
